---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl-material
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: youtubedl-material
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  timeout: 30m
  values:
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        # external-dns/is-public: "true"
        # external-dns.alpha.kubernetes.io/target: "gateway.${SECRET_DOMAIN}"
      hosts:
        - host: "youtubedl.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "youtubedl.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: youtubedl-material-config
        mountPath: /app/appdata
      audio:
        enabled: true
        existingClaim: youtubedl-material-audio
        mountPath: /app/audio
      subscriptions:
        enabled: false
      users:
        enabled: false
      video:
        enabled: true
        existingClaim: youtubedl-material-video
        mountPath: /app/video
