---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbdplugin-snapclass
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: rbd.csi.ceph.com
parameters:
  clusterID: 83ef3c72-c17b-4b1d-b89f-512d8d08268c
  csi.storage.k8s.io/snapshotter-secret-name: ceph-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: ceph
deletionPolicy: Delete
