---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: home
  namespace: kasten-io
spec:
  comment: ""
  frequency: "@daily"
  actions:
    - action: backup
      backupParameters:
        profile:
          namespace: kasten-io
          name: backblaze-b2
    - action: export
      exportParameters:
        frequency: "@daily"
        migrationToken:
          name: ""
          namespace: ""
        profile:
          name: backblaze-b2
          namespace: kasten-io
        receiveString: ""
        exportData:
          enabled: true
      retention:
        daily: 0
        weekly: 0
        monthly: 0
        yearly: 0
  retention:
    daily: 7
    weekly: 2
    monthly: 0
    yearly: 0
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - home
