---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: media
  namespace: kasten-io
spec:
  frequency: "@daily"
  actions:
    - action: backup
      backupParameters:
        profile:
          namespace: kasten-io
          name: backblaze-b2
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: backblaze-b2
          namespace: kasten-io
        exportData:
          enabled: true
      retention:
        daily: 14
  retention:
    daily: 14
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - media
